dataset: dataset6
title: 2008 MOST IMPORTANT PROBLEM MASTER CODES
questions: []
notes:
- 'Most Important Political Problem:'
- MIPPOL1_Code1 to MIPPOL1_Code8
- MIPPOL1_Substantive1 to MIPPOL1_Substantive8
- 'Second Most Important Political Problem:'
- MIPPOL2_Code1 to MIPPOL2_Code8
- MIPPOL2_Substantive1 to MIPPOL2_Substantive8
- 'Most Important Election Issue:'
- MIIELE1_Code1 to MIIELE1_Code8
- MIIELE1_Substantive1 to MIIELE1_Substantive8
- 'Second Most Important Election Issue:'
- MIIELE2_Code1 to MIIELE2_Code8
- MIIELE2_Substantive1 to MIIELE2_Substantive8
codes:
  '1': 'Defense spending: The defense budget or the amount of money spent for national defense, for the military, for military personnel, or for weapons'
  '2': 'Middle East: The Middle East, War or conflict in the Middle East, or wars or conflicts involving Middle Eastern countries except Iraq NOTE: References to “the war” are assigned code 4 War'
  '3': 'Iraq: The war in Iraq, Iraq NOTE: References to “the war” are assigned code 4 War'
  '4': 'War: Any war or military conflict other than the wars in Iraq or the Middle East, war in general, the war, or preventing or stopping war'
  '5': 'Terrorism: Terrorism, terrorist groups, terrorist acts, security, national security, or homeland security'
  '6': 'Veterans: Military veterans or benefits for military veterans'
  '7': 'National defense (all other): Any mention of national defense, the military, war, or military conflicts that does not match a description in codes 1-6'
  '8': 'Foreign aid: The amount of money the U.S. gives to other countries'
  '9': 'Foreign trade: Trade with other countries, imports and exports'
  '10': 'Protection of US jobs: Jobs moving from the U.S. to other countries; The protection of U.S. jobs and businesses from moving to other countries.'
  '11': 'Serbia/Balkans: The U.S. or NATO involvement in Serbia or the Balkans NOTE: References to war in Serbia or the Balkans are assigned code 4 War'
  '12': 'China: China NOTE: References to war in China are assigned code 4 War'
  '13': 'International affairs (all other): Any mention of a country other than the U.S., or U.S. relations with another country that does not match a description in codes 8-12'
  '14': 'Energy crisis: Fuel shortages, an energy crisis, or the development of different types of energy'
  '15': 'Energy prices: The cost of fuel or energy'
  '16': 'Energy (all other): Any mention of fuel or energy than does not match a description in codes 14-15'
  '17': 'Environment: Protecting the environment, conservation, ecology, global warming, preserving or restoring natural resources, pollution, clean air or water, radioactive waste, dumps, or landfills'
  '18': 'Natural resources (all other): Any mention of natural resources or the environment that does not match the description in code 17'
  '19': 'Education and training: Teacher training, education for teachers'
  '20': 'School funding: Funding for schools, colleges, or universities'
  '21': 'Education (all other): Any mention of education that does not match a description in codes 19-20'
  '22': 'Aids: AIDS or HIV'
  '23': 'Medicare: Medicare'
  '24': 'Health (all other): Any mention of health, a health issue, health problem, health care ,or disease that does not match the description in code 22-23'
  '25': 'Welfare: Welfare, welfare programs, welfare reform or helping the poor'
  '26': 'Poverty: Poverty, poor people, being poor, hunger, homelessness, food problems, food shortages, or starvation'
  '27': 'Employment: Employment, unemployment, jobs, the number of jobs, the job market, people losing jobs, job security, or people without jobs'
  '28': 'Housing: Housing, public housing, the government providing homes or housing for poor people, housing foreclosures, or the cost of buying a home'
  '29': 'Social security: Social Security'
  '30': 'Income (all other): Any mention of income, wages, benefits, or salaries that does not match a description in codes 25-29'
  '31': 'Crime: Crime or violence'
  '32': 'Race relations: Racial problems, racial violence, race relations, racial discrimination, reverse discrimination, discrimination against people who are not part of a minority group'
  '33': 'Illegal drugs: Any mention of the use or availability of illegal drugs, the sale of illegal drugs, or bringing illegal drugs into the U.S.'
  '34': 'Police problems: Police, police brutality, or the job police officers do'
  '35': 'Guns: Guns, gun control, or the availability of guns'
  '36': 'Corporate corruption: Corporate corruption, companies breaking the law, greed, fraud, or people abusing power in business and industry'
  '37': 'Justice (all other): Any mention of crime, law and order, the legal system, courts, rights, jails or prisons, executing people who are convicted of murder, the constitution, or any other legal issue that does not match a description in codes 31-36'
  '38': 'Budget: The budget, federal budget, deficit, budget deficit, debt, national debt, the cost of government , or wages or salaries of politicians or government workers in general NOTE: If an idea mentions the amount of money spent “on” something or “for” something, do not assign code 38 Budget to the idea. Ideas about money spent “on” or “for” something should be coded under the specific program that is mentioned'
  '39': 'Size of government: Big government, the size of the federal government, government bureaucracy, government rules and regulations, government paperwork, or government red tape'
  '40': 'Taxes: Taxes'
  '41': 'Immigration: Immigration, immigrants, illegal immigration, or immigration policy'
  '42': 'Campaign finance: The amount of money spent on political campaigns, laws that limit how much people can give to a political candidate, laws that limit how much money a candidate can spend for a campaign'
  '43': 'Political corruption: Crimes or illegal acts by politicians or a politician'
  '44': 'Ethics: Dishonest or unethical behaviors by a politician or politicians that are not illegal'
  '45': 'Government power: The power of the federal government to control people’s lives'
  '46': 'Budget priorities: Budget priorities, wasteful spending, or pork-barrel legislation'
  '47': 'Partisan politics: Partisanship or political parties, politicians or parties not working together, politicians or parties fighting with each other'
  '48': 'Politicians: Politicians, a specific politician, gridlock, or the balance of power'
  '49': 'Government (all other): Any other reference to government or politicians that does not match a description in codes 38-48'
  '50': 'The economy: Any mention of the economy or economic problems in general, economic crisis, finances, or financial problems'
  '51': 'Stock market: The stock market, gold prices, wall street, or stock brokers'
  '52': 'Economic inequality: The difference between the rich and poor'
  '53': 'Recession: Recession or economic slowdown'
  '54': 'Inflation: The cost of products and services that people buy. NOTE: References to energy costs are assigned code 15 Energy prices'
  '55': 'Economics (all other): Any mention of the economy, money, credit, labor, unions, businesses, jobs, or productivity that does not match a description in codes 50-54'
  '56': 'Agriculture: Farming, farms, cost of farming, farm or crop subsidies, government programs or money for farms or farming, or agriculture problems'
  '57': 'Science: Science, technology, computers, the internet, or the space program'
  '58': 'Commerce: Businesses that the government sponsors, the United States Postal Service, USPS, Fannie Mae, Freddie Mac, Federal Deposit Insurance Corporation, FDIC'
  '59': 'Transportation: The automobile industry, automobile safety, airports or airlines, ships, highways, highways, roads, bridges, railways, public transportation, or any form of travel'
  '60': 'Community development: Programs to improve community economic conditions, promote rural development, assist in federal preparations for and response to disasters, the Federal Emergency Management Agency, FEMA'
  '61': 'Abortion: Any mention of abortion or a woman’s right to obtain an abortion'
  '62': 'Child care: Businesses that care for young children during the day'
  '63': 'Overpopulation: The number of people in the country or on the earth'
  '64': 'Public morality: Public morals, morality, religion, a specific religion, sex, or bad language NOTE: References to “Church and State” are assigned code 49 Government (all other)'
  '65': 'Domestic violence: Child abuse, spouse abuse, abuse of older people, or abuse in retirement homes, nursing homes, assisted living facilities, or other places in which older people live'
  '66': 'Family: Families, protecting the family, or family values'
  '67': 'Young people: Problems, values, goals, ambition, sense or respect, or sense of responsibility among young people,'
  '68': 'Homosexuality: Gays and lesbians, gay and lesbian rights, or gay and lesbian marriage'
  '69': 'The media: Media, news, television, radio, newspapers, magazines, or the internet'
  '70': 'Everything: Everything'
  '71': 'Other: Any other problem that cannot be coded as any of the above categories'
